name: 'Linters'

on:
  pull_request:
    branches: [develop, lss-mobi, release/**, feature/**]

jobs:
  linters-checking:
    name: Check project linting

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn eslint
